namespace SagePay.IntegrationKit.Standard
{
    public enum CardType
    {
        NONE,
        VISA,
        MC,
        DELTA,
        MAESTRO,
        UKE,
        AMEX,
        DC,
        JCB,
        LASER,
        PAYPAL,
        SWITCH,
        [SagePayProtocolVersion(ProtocolVersion.V_300)]
        PLCC,
        [SagePayProtocolVersion(ProtocolVersion.V_300)]
        MCDEBIT,
        [SagePayProtocolVersion(ProtocolVersion.V_300)]
        EPS,
        [SagePayProtocolVersion(ProtocolVersion.V_300)]
        GIROPAY,
        [SagePayProtocolVersion(ProtocolVersion.V_300)]
        IDEAL,
        [SagePayProtocolVersion(ProtocolVersion.V_300)]
        SOFORT,
        [SagePayProtocolVersion(ProtocolVersion.V_300)]
        ELV
    }
}